version: "3.9"

services:
  web:
    build: .
    ports: ["5000:5000"]
    environment:
      - DB_URI=postgresql+psycopg2://postgres:postgres@db:5432/musicdb
      - SPOTIFY_TOKEN=${SPOTIFY_TOKEN}
      - VK_TOKEN=${VK_TOKEN}
    depends_on: [db]

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: musicdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
